Initial changes for Device Mode Support
rudderlabs/rudder-sdk-flutter pull request #49
Opened 2022-08-03 14:08 UTC by desusai7

## Description of the change

> Initial changes for Device Mode Support

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2022-10-12 06:06 UTC, pallabmaiti requested changes
1. Can you change every summary, description, author, homepage of `podspec` files? For example: `s.summary = 'A new Flutter plugin project.'`
2. I can see lots of `gitignore`. Can you remove all & keep only one?

2022-10-12 06:06 UTC, pallabmaiti commented on rudder_plugin/CHANGELOG.md
> +    Updated the rudder_plugin_android & rudder_plugin_ios versions
Add the changelog here.

2022-10-18 05:20 UTC, desusai7 commented on rudder_plugin/CHANGELOG.md
> +    Updated the rudder_plugin_android & rudder_plugin_ios versions
Added

2022-10-18 05:23 UTC, desusai7 commented
1. Updated the podspec files of all the iOS modules of the Flutter Device Mode
2. Yes, there were multiple .gitignore files, as they were automatically generated by flutter, and thought it would be better to keep them as they were, as each of them are dealing with the platform specific files, but yeah we can merge them if we want to.

2022-10-18 05:37 UTC, pallabmaiti approved these changes

2022-10-18 05:59 UTC, merged